### ISSUE TITLE
Assignment 1 ready for grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [SES-5215-F2020/alexcox-quant#1]
Hi all, I have uploaded my Rmd and HTML files for grading. I will appreciate any feedback you provide!

**Comment by saratepfer** [comment]
**Comments on content**
It would be helpful to explicitly state/describe what is included in your population. For example: "My population includes military and non-military commuters in the state of Virginia" or similar. Also, you say "In order to conduct an analysis of commute patterns for military service members...", but it looks like you are looking at both military service members and non-service members. I would consider revising this sentence for consistency.

**Comments on code**
**Line 8:** You can remove the messages that appear after you load your packages by using: ```{r messages = FALSE}
**N/A (less than 17 years old)** You can filter this out if you'd like using an additional filter below line 37: filter(MIL_label != "N/A (less than 17 years old)")
