### ISSUE TITLE
Assignment 2 Ready for Grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [SES-5215-F2020/alexcox-quant#2]
Hello, my Assignment 2 Rmd and HTML files are ready for grading, they are both called "Assignment 2." Thank you!

**Comment by saratepfer** [comment]
Thank you, Alex! Nice job on this! A few comments below. 

**Comments on Code**
- Lines 63-65: It may be helpful to add a 1-2 numbers after the decimal place to better understand your 95% confidence interval. (it is currently 29-29 minutes, which could be clarified.)
- Was your use of scientific notation intentional in reporting the mean and standard deviation for your PINCP variable? If so, I would use scientific notation consistently across each of the descriptive statistics, rather than using two different notations as you currently have it.

**Comments on Content**
- The histograms are helpful visualizations, but it would also be nice to have a sentence or two interpretation of each of them.
- The calculations you show for the proportions and 95% CIs for your categorical variables are good, but they are not very legible. I recommend compiling them into a table, either within R (per Catherine's example assignment), or in a document generated outside of R.
