### ISSUE TITLE
Assignment 3 ready for grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [SES-5215-F2020/alexcox-quant#3]
Hi all, my Assignment 3 RMD and HTML files are ready for grading! The link to the HTML is below:

https://ses-5215-f2020.github.io/alexcox-quant/Assignment-3---Quant.html

**Comment by saratepfer** [comment]
Great job, Alex! Please find a few comments below. 

- On your chi square test, it looks like the relationship between military status and commuters using car, truck, or van is also statistically significant.
- You can run a single chi square test instead of running them all individually using: "chi_sq <- chisq.test(military_data$MIL_label, military_data$JWTR_label"
- Line 176: in addition to commenting on the strength of the correlation, it is also important to comment on the significance of the relationship using the p-value.
- Similar lines 195 and 217. 
- ANOVA doesn't tell you the strength of the correlation, so you can't comment on that, but you can say whether or not it is a significant correlation (lines 237, 259, 359).
